/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crudpigs;

import cruduser.*;
import admin_interface.Admin_dashboard;
import config.Session;
import config.dbconnect;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import psms.mariquit.login;
import user_interface.User_dashboard;


public class allpigs extends javax.swing.JFrame {

 
    public allpigs() {
        initComponents();
        displayData();
       pigstable.getTableHeader().setOpaque(false);
       pigstable.getTableHeader().setBackground(new java.awt.Color(0,204,153));

    }   
        public void displayData(){
        try{
            dbconnect dbc = new dbconnect();
            try (ResultSet rs = dbc.getData("SELECT id,  breed, price, status FROM pigs ")) {
                pigstable.setModel(DbUtils.resultSetToTableModel(rs));

                TableColumnModel columnModel = pigstable.getColumnModel();
                columnModel.getColumn(0).setHeaderValue("ID");
                columnModel.getColumn(1).setHeaderValue("breed");
                columnModel.getColumn(2).setHeaderValue("price");
                columnModel.getColumn(3).setHeaderValue("status");
                pigstable.getTableHeader().repaint();
                
            }
        }catch(SQLException ex){
            System.out.println("Errors: "+ex.getMessage());

        }

    }

    public void searchdata(){
    try{
        dbconnect dbc = new dbconnect();
        
        String keyword = search.getText().trim();

        // If search box is empty, show all data
        if(keyword.isEmpty()){
            displayData();
            return;
        }

        String query = "SELECT id, breed, price, status FROM pigs "
                     + "WHERE id LIKE '%" + keyword + "%' "
                     + "OR breed LIKE '%" + keyword + "%' "
                     + "OR price LIKE '%" + keyword + "%' "
                     + "OR status LIKE '%" + keyword + "%'";

        ResultSet rs = dbc.getData(query);

        // If no result found
        if (!rs.isBeforeFirst()) {
            JOptionPane.showMessageDialog(null, "No records found.");
            displayData();
            return;
        }

        pigstable.setModel(DbUtils.resultSetToTableModel(rs));

        // Set column headers
        TableColumnModel columnModel = pigstable.getColumnModel();
        columnModel.getColumn(0).setHeaderValue("ID");
        columnModel.getColumn(1).setHeaderValue("Breed");
        columnModel.getColumn(2).setHeaderValue("Price");
        columnModel.getColumn(3).setHeaderValue("Status");
        pigstable.getTableHeader().repaint();

    }catch(SQLException ex){
        System.out.println("Errors: "+ex.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addpig = new javax.swing.JLabel();
        edituser = new javax.swing.JLabel();
        deletepig = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        uname = new javax.swing.JLabel();
        utype = new javax.swing.JLabel();
        usertype = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        details = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pigstable = new javax.swing.JTable();
        id = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addpig.setBackground(new java.awt.Color(0, 204, 153));
        addpig.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addpig.setForeground(new java.awt.Color(255, 255, 255));
        addpig.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addpig.setText("ADD PIG");
        addpig.setOpaque(true);
        addpig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addpigMouseClicked(evt);
            }
        });
        jPanel1.add(addpig, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 300, 60));

        edituser.setBackground(new java.awt.Color(0, 204, 153));
        edituser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edituser.setForeground(new java.awt.Color(255, 255, 255));
        edituser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        edituser.setText("EDIT PIG");
        edituser.setOpaque(true);
        edituser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edituserMouseClicked(evt);
            }
        });
        jPanel1.add(edituser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 300, 60));

        deletepig.setBackground(new java.awt.Color(0, 204, 153));
        deletepig.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deletepig.setForeground(new java.awt.Color(255, 255, 255));
        deletepig.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deletepig.setText("DELETE PIG");
        deletepig.setOpaque(true);
        deletepig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletepigMouseClicked(evt);
            }
        });
        jPanel1.add(deletepig, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 300, 60));

        back.setBackground(new java.awt.Color(0, 204, 153));
        back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setText("BACK");
        back.setOpaque(true);
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 300, 60));

        uname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        uname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 570, 490, 30));

        utype.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        utype.setForeground(new java.awt.Color(255, 255, 255));
        utype.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(utype, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 200, 40));

        usertype.setBackground(new java.awt.Color(0, 204, 153));
        usertype.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        usertype.setForeground(new java.awt.Color(255, 255, 255));
        usertype.setText("MANAGE PIGS");
        usertype.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        usertype.setOpaque(true);
        jPanel1.add(usertype, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("OPTIONS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 300, 50));

        details.setBackground(new java.awt.Color(0, 204, 153));
        details.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        details.setForeground(new java.awt.Color(255, 255, 255));
        details.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        details.setText("VIEW DETAIL");
        details.setOpaque(true);
        details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detailsMouseClicked(evt);
            }
        });
        jPanel1.add(details, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 300, 60));

        pigstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        pigstable.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(pigstable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 760, 520));

        id.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        id.setText("id");
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 90, 40));
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 380, 40));

        jLabel2.setBackground(new java.awt.Color(0, 204, 153));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SEARCH");
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 50, 190, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addpigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addpigMouseClicked
        addpig.setOpaque(true);
        addpig.setBackground(Color.white);
        addpig.setForeground(new java.awt.Color(0,153,0));
        back.setOpaque(true);
        back.setForeground(Color.white);
        back.setBackground(new java.awt.Color(0,153,0));

        addpigs add = new addpigs();
        add.setVisible(true);
        add.delete.setEnabled(false);

        this.dispose();
    }//GEN-LAST:event_addpigMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        back.setOpaque(true);
        back.setBackground(Color.white);
        back.setForeground(new java.awt.Color(0,153,0));
        
        if(utype.getText().equals("Admin")){
                Admin_dashboard admdash = new Admin_dashboard();
                admdash.setVisible(true);
               this.dispose();
               
        }else if(utype.getText().equals("User")){
                User_dashboard usrdash = new User_dashboard();
                usrdash.setVisible(true);
                this.dispose();            
            }
    }//GEN-LAST:event_backMouseClicked

    private void detailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detailsMouseClicked
        int rowIndex = pigstable.getSelectedRow();

        if (rowIndex < 0) {
            JOptionPane.showMessageDialog(null, "Please select an item!");
        } else {
            try {
                dbconnect dbc = new dbconnect();
                TableModel tbl = pigstable.getModel();
                ResultSet rs = dbc.getData("SELECT * FROM pigs WHERE id = '" + tbl.getValueAt(rowIndex, 0) + "'");

                if (rs.next()) {

                    pigview view = new pigview();
                    view.id.setText(""+rs.getInt("id"));
                    view.age.setText(""+rs.getString("age"));
                    view.breed.setText(""+rs.getString("breed"));
                    view.weight.setText(""+rs.getString("weight"));
                    view.status.setText(""+rs.getString("status"));
                    view.price.setText(""+rs.getString("price"));


                   view.setVisible(true);
                   this.dispose();
                }

            } catch (SQLException ex) {
                System.out.println("" + ex);
            }
        }    
    }//GEN-LAST:event_detailsMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       Session sess = Session.getInstance();
        if(sess.getId() == 0){
        JOptionPane.showMessageDialog(null,"No account found, login first!");
        login lfm = new login();
        lfm.setVisible(true);
        this.dispose();
        }else{
        
        utype.setText(""+sess.getType());

        }
    }//GEN-LAST:event_formWindowActivated

    private void edituserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edituserMouseClicked
int rowIndex = pigstable.getSelectedRow();

        if (rowIndex < 0) {
            JOptionPane.showMessageDialog(null, "Please select an item!");
        } else {
            try {
                dbconnect dbc = new dbconnect();
                TableModel tbl = pigstable.getModel();
                ResultSet rs = dbc.getData("SELECT * FROM pigs WHERE id = '" + tbl.getValueAt(rowIndex, 0) + "'");

                if (rs.next()) {

                    addpigs add = new addpigs();
                    add.id.setText(""+rs.getInt("id"));
                    add.breed.setText(""+rs.getString("breed"));
                    add.price.setText(""+rs.getString("price"));
                    add.weight.setText(""+rs.getString("weight"));
                    add.age.setText(""+rs.getString("age"));
                    add.status.setSelectedItem(""+rs.getString("status"));
                    add.add.setEnabled(false);
                    add.edit.setEnabled(true);
                    add.delete.setEnabled(false);
                   add.setVisible(true);
                   this.dispose();
                }

            } catch (SQLException ex) {
                System.out.println("" + ex);
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_edituserMouseClicked

    private void deletepigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletepigMouseClicked
      int rowIndex = pigstable.getSelectedRow();

        if (rowIndex < 0) {
            JOptionPane.showMessageDialog(null, "Please select an item!");
        } else {
            try {
                dbconnect dbc = new dbconnect();
                TableModel tbl = pigstable.getModel();
                ResultSet rs = dbc.getData("SELECT * FROM pigs WHERE id = '" + tbl.getValueAt(rowIndex, 0) + "'");

                if (rs.next()) {

                    addpigs add = new addpigs();
                    add.id.setText(""+rs.getInt("id"));
                    add.breed.setText(""+rs.getString("breed"));
                    add.price.setText(""+rs.getString("price"));
                    add.weight.setText(""+rs.getString("weight"));
                    add.age.setText(""+rs.getString("age"));
                    add.status.setSelectedItem(""+rs.getString("status"));
                    add.add.setEnabled(false);
                    add.edit.setEnabled(false);
                   add.setVisible(true);
                   this.dispose();
                }

            } catch (SQLException ex) {
                System.out.println("" + ex);
            }
        }   

    }//GEN-LAST:event_deletepigMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        if(search.getText().isEmpty()){
        }
        else{
        searchdata();}
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(allpigs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(allpigs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(allpigs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(allpigs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new allpigs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addpig;
    private javax.swing.JLabel back;
    public javax.swing.JLabel deletepig;
    private javax.swing.JLabel details;
    private javax.swing.JLabel edituser;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable pigstable;
    private javax.swing.JTextField search;
    private javax.swing.JLabel uname;
    private javax.swing.JLabel usertype;
    private javax.swing.JLabel utype;
    // End of variables declaration//GEN-END:variables
}
