/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transaction;

import cruduser.*;
import admin_interface.Admin_dashboard;
import config.Session;
import config.dbconnect;
import config.passwordHasher;
import java.awt.Color;
import java.security.NoSuchAlgorithmException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableColumnModel;
import net.proteanit.sql.DbUtils;
import psms.mariquit.login;
import user_interface.User_dashboard;


public class addtransact extends javax.swing.JFrame {

    /**
     * Creates new form allusers
     */
    public addtransact() {
        initComponents();
       

    }   
       
public void loadcustomers() {
    try {
         dbconnect dbc = new dbconnect();
        String sql = "SELECT userid, fullname FROM users";
        PreparedStatement pst = dbc.connect.prepareStatement(sql);
        ResultSet Rss = pst.executeQuery();
        
        
        customers.removeAllItems();
        
        while (Rss.next()) {
            String position = Rss.getString("fullname");
            customers.addItem(position);
        }

    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error loading customer: " + ex.getMessage());
    }
}


public void loadpigs(){
    try {
         dbconnect dbc = new dbconnect();

        String sql = "SELECT id, breed FROM pigs";
        PreparedStatement pst = dbc.connect.prepareStatement(sql);
        ResultSet Rss = pst.executeQuery();    
        pig.removeAllItems();
        while (Rss.next()) {
            String position = Rss.getString("breed");
            pig.addItem(position);
        }

    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error loading positions: " + ex.getMessage());
    }
}   

    public static int uid,pid, price;
    
     public boolean getids(){ 
       dbconnect dbc = new dbconnect();
     try {    
             
        String queryusers = "SELECT * FROM users WHERE fullname = '" + customers.getSelectedItem().toString() + "'";
        String querypig = "SELECT * FROM pigs WHERE breed = '" + pig.getSelectedItem().toString() + "'";

        ResultSet rsu = dbc.getData(queryusers);
        ResultSet rsp = dbc.getData(querypig);
        boolean valid = true;

        if (rsu.next()) {
            uid = rsu.getInt("userid");
        } else {
            valid = false;
        }

        if (rsp.next()) {
            pid = rsp.getInt("id");
            price = rsp.getInt("price");
        } else {
            valid = false;
        }

        return valid;
        } catch (SQLException ex) {
            System.out.println(""+ex);
            return false;
        }    
    }      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        add = new javax.swing.JLabel();
        edit = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        uname = new javax.swing.JLabel();
        utype = new javax.swing.JLabel();
        usertype = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        payment = new javax.swing.JTextField();
        sd = new javax.swing.JLabel();
        pig = new javax.swing.JComboBox<>();
        customers = new javax.swing.JComboBox<>();
        id = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        delete = new javax.swing.JLabel();
        status = new javax.swing.JComboBox<>();
        total = new javax.swing.JTextField();
        pigid = new javax.swing.JTextField();
        cusid = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        back1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add.setBackground(new java.awt.Color(51, 204, 0));
        add.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add.setText("ADD ");
        add.setOpaque(true);
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 210, 50));

        edit.setBackground(new java.awt.Color(51, 204, 0));
        edit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edit.setForeground(new java.awt.Color(255, 255, 255));
        edit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        edit.setText("EDIT");
        edit.setEnabled(false);
        edit.setOpaque(true);
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        jPanel1.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 210, 50));

        back.setBackground(new java.awt.Color(51, 204, 0));
        back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setText("BACK");
        back.setOpaque(true);
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 210, 50));

        uname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        uname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 570, 490, 30));

        utype.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        utype.setForeground(new java.awt.Color(255, 255, 255));
        utype.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(utype, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 200, 40));

        usertype.setBackground(new java.awt.Color(51, 204, 0));
        usertype.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        usertype.setForeground(new java.awt.Color(255, 255, 255));
        usertype.setText("ADD TRANSACTION");
        usertype.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        usertype.setOpaque(true);
        jPanel1.add(usertype, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 40));

        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });
        jPanel1.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 350, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 0));
        jLabel11.setText("Payment:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 350, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 0));
        jLabel13.setText("pig:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 350, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 0));
        jLabel12.setText("customer id:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 180, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 0));
        jLabel3.setText("Status");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 350, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 0));
        jLabel7.setText("transact id:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 350, -1));
        jPanel1.add(payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 350, 40));

        sd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sd.setForeground(new java.awt.Color(0, 153, 0));
        sd.setText("total:");
        jPanel1.add(sd, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 350, -1));

        jPanel1.add(pig, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 350, 40));

        jPanel1.add(customers, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 350, 40));

        id.setEnabled(false);
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 350, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 0));
        jLabel9.setText("customer:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 350, -1));

        delete.setBackground(new java.awt.Color(51, 204, 0));
        delete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        delete.setText("DELETE");
        delete.setOpaque(true);
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 210, 50));

        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Approved", "Canceled" }));
        jPanel1.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 350, 40));
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, 350, 40));
        jPanel1.add(pigid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 180, 30));
        jPanel1.add(cusid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 180, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 0));
        jLabel14.setText("pig id:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 180, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 0));
        jLabel15.setText("Quantity:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 350, -1));

        back1.setBackground(new java.awt.Color(51, 204, 0));
        back1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        back1.setForeground(new java.awt.Color(255, 255, 255));
        back1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back1.setText("REVIEW DETAILS");
        back1.setOpaque(true);
        back1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back1MouseClicked(evt);
            }
        });
        jPanel1.add(back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 260, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
          if (getids()){
              dbconnect dbc = new dbconnect();
        int qty = Integer.parseInt(quantity.getText());
        int ttl = price * qty;
        
        int db = dbc.insertData("INSERT INTO transacts(uid, pid,status,quantity, payment,total) VALUES ('"
                 + uid + "', '"
                 + pid + "', '"
                 + status.getSelectedItem()+ "', '"
                 + quantity.getText() + "', '"
                 + payment.getText() + "', '"
                 + ttl +"')");
         JOptionPane.showMessageDialog(null,"transaction created successfully.");

          }
        
    }//GEN-LAST:event_addMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        back.setOpaque(true);
        back.setBackground(Color.white);
        back.setForeground(new java.awt.Color(0,153,0));

        if(utype.getText().equals("Admin")){
                Admin_dashboard admdash = new Admin_dashboard();
                admdash.setVisible(true);
               this.dispose();
               
        }else if(utype.getText().equals("User")){
                User_dashboard usrdash = new User_dashboard();
                usrdash.setVisible(true);
                this.dispose();            
            }
    }//GEN-LAST:event_backMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       Session sess = Session.getInstance();
        if(sess.getId() == 0){
        JOptionPane.showMessageDialog(null,"No account found, login first!");
        login lfm = new login();
        lfm.setVisible(true);
        this.dispose();
        }else{
        
        utype.setText(""+sess.getType());
        loadpigs();
        loadcustomers();
        }
    }//GEN-LAST:event_formWindowActivated

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseClicked
 

    }//GEN-LAST:event_editMouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
    Session sess = Session.getInstance();
    dbconnect dbc = new dbconnect();
         dbc.deleteData("DELETE FROM transacts WHERE id = '"+  id.getText() +"'");
            JOptionPane.showMessageDialog(null, "Deleted successfully");
            alltransact all = new alltransact();
            all.setVisible(true);
            this.disable();// TODO add your handling code here:
    }//GEN-LAST:event_deleteMouseClicked

    private void back1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back1MouseClicked
          if (getids()){
          if(uid == 0 || pid == 0){
        JOptionPane.showMessageDialog(null, "select customer or pigs first");
        }else{
        cusid.setText(String.valueOf(uid));
        pigid.setText(String.valueOf(pid));
        int qty = Integer.parseInt(quantity.getText());
        int ttl = price * qty;
        total.setText(String.valueOf(ttl));
        
        }     
          }
        
    }//GEN-LAST:event_back1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addtransact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addtransact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addtransact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addtransact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addtransact().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel add;
    private javax.swing.JLabel back;
    private javax.swing.JLabel back1;
    private javax.swing.JTextField cusid;
    public javax.swing.JComboBox<String> customers;
    public javax.swing.JLabel delete;
    public javax.swing.JLabel edit;
    public javax.swing.JTextField id;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField payment;
    public javax.swing.JComboBox<String> pig;
    private javax.swing.JTextField pigid;
    public javax.swing.JTextField quantity;
    private javax.swing.JLabel sd;
    public javax.swing.JComboBox<String> status;
    public javax.swing.JTextField total;
    private javax.swing.JLabel uname;
    private javax.swing.JLabel usertype;
    private javax.swing.JLabel utype;
    // End of variables declaration//GEN-END:variables
}
