/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transaction;

import cruduser.*;
import admin_interface.Admin_dashboard;
import config.Session;
import config.dbconnect;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import psms.mariquit.login;
import user_interface.User_dashboard;


public class alltransact extends javax.swing.JFrame {

    /**
     * Creates new form allusers
     */
    public alltransact() {
        initComponents();
        displayData();
       userstable.getTableHeader().setOpaque(false);
       userstable.getTableHeader().setBackground(new java.awt.Color(0,153,0));

    }   
        public void displayData(){
        try{
            dbconnect dbc = new dbconnect();
            try (ResultSet rs = dbc.getData("SELECT userid, fullname, email, usertype, status FROM users ")) {
                userstable.setModel(DbUtils.resultSetToTableModel(rs));

                TableColumnModel columnModel = userstable.getColumnModel();
                columnModel.getColumn(0).setHeaderValue("ID");
                columnModel.getColumn(1).setHeaderValue("Full name");
                columnModel.getColumn(2).setHeaderValue("Email");
                columnModel.getColumn(3).setHeaderValue("User type");
                columnModel.getColumn(4).setHeaderValue("User status");
                userstable.getTableHeader().repaint();
                
            }
        }catch(SQLException ex){
            System.out.println("Errors: "+ex.getMessage());

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        adduser = new javax.swing.JLabel();
        edituser = new javax.swing.JLabel();
        deleteuser = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        uname = new javax.swing.JLabel();
        utype = new javax.swing.JLabel();
        usertype = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        details = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userstable = new javax.swing.JTable();
        id = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adduser.setBackground(new java.awt.Color(51, 204, 0));
        adduser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        adduser.setForeground(new java.awt.Color(255, 255, 255));
        adduser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adduser.setText("ADD TRANSACTION");
        adduser.setOpaque(true);
        adduser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adduserMouseClicked(evt);
            }
        });
        jPanel1.add(adduser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 300, 60));

        edituser.setBackground(new java.awt.Color(51, 204, 0));
        edituser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edituser.setForeground(new java.awt.Color(255, 255, 255));
        edituser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        edituser.setText("EDIT TRANSACTION");
        edituser.setOpaque(true);
        edituser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edituserMouseClicked(evt);
            }
        });
        jPanel1.add(edituser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 300, 60));

        deleteuser.setBackground(new java.awt.Color(51, 204, 0));
        deleteuser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deleteuser.setForeground(new java.awt.Color(255, 255, 255));
        deleteuser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deleteuser.setText("DELETE TRANSACTION");
        deleteuser.setOpaque(true);
        deleteuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteuserMouseClicked(evt);
            }
        });
        jPanel1.add(deleteuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 300, 60));

        back.setBackground(new java.awt.Color(51, 204, 0));
        back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setText("BACK");
        back.setOpaque(true);
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 300, 60));

        uname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        uname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 570, 490, 30));

        utype.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        utype.setForeground(new java.awt.Color(255, 255, 255));
        utype.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(utype, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 200, 40));

        usertype.setBackground(new java.awt.Color(51, 204, 0));
        usertype.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        usertype.setForeground(new java.awt.Color(255, 255, 255));
        usertype.setText("MANAGE USERS");
        usertype.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        usertype.setOpaque(true);
        jPanel1.add(usertype, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("OPTIONS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 300, 50));

        details.setBackground(new java.awt.Color(51, 204, 0));
        details.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        details.setForeground(new java.awt.Color(255, 255, 255));
        details.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        details.setText("VIEW DETAIL");
        details.setOpaque(true);
        details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detailsMouseClicked(evt);
            }
        });
        jPanel1.add(details, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 300, 60));

        userstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        userstable.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(userstable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 760, 570));

        id.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        id.setText("id");
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 90, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adduserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adduserMouseClicked
        adduser.setOpaque(true);
        adduser.setBackground(Color.white);
        adduser.setForeground(new java.awt.Color(0,153,0));
        back.setOpaque(true);
        back.setForeground(Color.white);
        back.setBackground(new java.awt.Color(0,153,0));

        addtransact add = new addtransact();
        add.setVisible(true);
        add.delete.setEnabled(false);

        this.dispose();
    }//GEN-LAST:event_adduserMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        back.setOpaque(true);
        back.setBackground(Color.white);
        back.setForeground(new java.awt.Color(0,153,0));
        
        if(utype.getText().equals("Admin")){
                Admin_dashboard admdash = new Admin_dashboard();
                admdash.setVisible(true);
               this.dispose();
               
        }else if(utype.getText().equals("User")){
                User_dashboard usrdash = new User_dashboard();
                usrdash.setVisible(true);
                this.dispose();            
            }
    }//GEN-LAST:event_backMouseClicked

    private void detailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detailsMouseClicked
  
    }//GEN-LAST:event_detailsMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       Session sess = Session.getInstance();
        if(sess.getId() == 0){
        JOptionPane.showMessageDialog(null,"No account found, login first!");
        login lfm = new login();
        lfm.setVisible(true);
        this.dispose();
        }else{
        
        utype.setText(""+sess.getType());

        }
    }//GEN-LAST:event_formWindowActivated

    private void edituserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edituserMouseClicked
       // TODO add your handling code here:
    }//GEN-LAST:event_edituserMouseClicked

    private void deleteuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteuserMouseClicked
 
    }//GEN-LAST:event_deleteuserMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(alltransact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(alltransact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(alltransact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(alltransact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new alltransact().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adduser;
    private javax.swing.JLabel back;
    private javax.swing.JLabel deleteuser;
    private javax.swing.JLabel details;
    private javax.swing.JLabel edituser;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel uname;
    private javax.swing.JTable userstable;
    private javax.swing.JLabel usertype;
    private javax.swing.JLabel utype;
    // End of variables declaration//GEN-END:variables
}
