/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transaction;

import cruduser.*;
import admin_interface.Admin_dashboard;
import config.Session;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import psms.mariquit.login;
import user_interface.User_dashboard;

/**
 *
 * @author Teves
 */
public class viewtransact extends javax.swing.JFrame {

    /**
     * Creates new form profileinfo
     */
    public viewtransact() {
        initComponents();
    }
        public static int getHeightFromWidth(String imagePath, int desiredWidth) {
        try {
            // Read the image file
            File imageFile = new File(imagePath);
            BufferedImage image = ImageIO.read(imageFile);
            
            // Get the original width and height of the image
            int originalWidth = image.getWidth();
            int originalHeight = image.getHeight();
            
            // Calculate the new height based on the desired width and the aspect ratio
            int newHeight = (int) ((double) desiredWidth / originalWidth * originalHeight);
            
            return newHeight;
        } catch (IOException ex) {
            System.out.println("No image found!");
        }
        
        return -1;
    }

    public  ImageIcon ResizeImage(String ImagePath, byte[] pic, JLabel label) {
    ImageIcon MyImage = null;
        if(ImagePath !=null){
            MyImage = new ImageIcon(ImagePath);
        }else{
            MyImage = new ImageIcon(pic);
        }
        
    int newHeight = getHeightFromWidth(ImagePath, label.getWidth());

    Image img = MyImage.getImage();
    Image newImg = img.getScaledInstance(label.getWidth(), newHeight, Image.SCALE_SMOOTH);
    ImageIcon image = new ImageIcon(newImg);
    return image;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fullname = new javax.swing.JLabel();
        cs = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        profile = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        cs1 = new javax.swing.JLabel();
        contact = new javax.swing.JLabel();
        cs2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        ts = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        breed = new javax.swing.JLabel();
        cs3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        price = new javax.swing.JLabel();
        cs4 = new javax.swing.JLabel();
        quantity = new javax.swing.JLabel();
        cs5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        status = new javax.swing.JLabel();
        cs7 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        total = new javax.swing.JLabel();
        cs6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1140, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fullname.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        fullname.setText("FULL NAME");
        jPanel1.add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 330, 40));

        cs.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cs.setText("Customer name:");
        jPanel1.add(cs, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 330, 30));

        jLabel8.setBackground(new java.awt.Color(51, 204, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("  TRANSACT INFORMATION");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel8.setOpaque(true);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 40));

        profile.setBackground(new java.awt.Color(51, 204, 0));
        profile.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        profile.setForeground(new java.awt.Color(255, 255, 255));
        profile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profile.setText("BACK");
        profile.setOpaque(true);
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
        });
        jPanel1.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 220, 40));

        address.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        address.setText("ADDRESS");
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 330, 40));

        cs1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cs1.setText("Customer address:");
        jPanel1.add(cs1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 340, 30));

        contact.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        contact.setText("CONTACT");
        jPanel1.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 150, 340, 40));

        cs2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cs2.setText("Customer contact:");
        jPanel1.add(cs2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 130, 320, 30));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ts.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ts.setText("transact ID:");
        jPanel5.add(ts, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 280, 30));

        id.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        id.setText("id");
        jPanel5.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 270, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 1080, 60));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 330, 90));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, 370, 90));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 340, 90));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        breed.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        breed.setText("BREED");
        jPanel6.add(breed, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 330, 40));

        cs3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cs3.setText("Pig breed:");
        jPanel6.add(cs3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 330, 30));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 340, 90));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        price.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        price.setText("PRICE");
        jPanel7.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 290, 40));

        cs4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cs4.setText("Pig price:");
        jPanel7.add(cs4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 290, 30));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 330, 90));

        quantity.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        quantity.setText("QUANTITY");
        jPanel1.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 350, 340, 40));

        cs5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cs5.setText("Quantity");
        jPanel1.add(cs5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 330, 320, 30));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 320, 370, 90));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        status.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        status.setText("STATUS");
        jPanel10.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 290, 40));

        cs7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cs7.setText("Status:");
        jPanel10.add(cs7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 290, 30));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, 520, 90));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        total.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        total.setText("TOTAL");
        jPanel9.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 330, 40));

        cs6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cs6.setText("Total:");
        jPanel9.add(cs6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 330, 30));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 540, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Session sess = Session.getInstance();
        if(sess.getId() == 0){
        JOptionPane.showMessageDialog(null,"No account found, login first!");
        login lfm = new login();
        lfm.setVisible(true);
        this.dispose();
        }else{
       
        }
    }//GEN-LAST:event_formWindowActivated

    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked
    alltransact all = new alltransact();
    all.setVisible(true);
    this.dispose();
    
    }//GEN-LAST:event_profileMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewtransact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewtransact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewtransact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewtransact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewtransact().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel address;
    public javax.swing.JLabel breed;
    public javax.swing.JLabel contact;
    public javax.swing.JLabel cs;
    public javax.swing.JLabel cs1;
    public javax.swing.JLabel cs2;
    public javax.swing.JLabel cs3;
    public javax.swing.JLabel cs4;
    public javax.swing.JLabel cs5;
    public javax.swing.JLabel cs6;
    public javax.swing.JLabel cs7;
    public javax.swing.JLabel fullname;
    public javax.swing.JLabel id;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    public javax.swing.JLabel price;
    private javax.swing.JLabel profile;
    public javax.swing.JLabel quantity;
    public javax.swing.JLabel status;
    public javax.swing.JLabel total;
    public javax.swing.JLabel ts;
    // End of variables declaration//GEN-END:variables
}
