/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package psms.mariquit;

import cruduser.*;
import admin_interface.Admin_dashboard;
import config.Session;
import config.dbconnect;
import config.passwordHasher;
import java.awt.Color;
import java.security.NoSuchAlgorithmException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static psms.mariquit.login.hashedpassword;
import user_interface.User_dashboard;


public class editpass extends javax.swing.JFrame {

    /**
     * Creates new form allusers
     */
    public editpass() {
        initComponents();
       

    }   
       

    
     public static String pass, npass, passs;
    
    public boolean duplicatecheck() throws NoSuchAlgorithmException{
        Session sess = Session.getInstance();  
        dbconnect dbc = new dbconnect();
   try {
            String query = "SELECT * FROM users WHERE userid = '"+sess.getId()+"'";
            ResultSet resultSet = dbc.getData(query);
            pass = passwordHasher.hashPassword(password.getText());
            npass = passwordHasher.hashPassword(newpass.getText());
             passs= resultSet.getString("password");
            if(resultSet.next()){ 
                if(!(pass.equals(passs))){
                JOptionPane.showMessageDialog(null,"password is incorrect");
                password.setText("");
                }
               
                return true;
            }else if(resultSet.next()){
                System.out.println(""+pass);
                System.out.println(""+passs);
                System.out.println(""+npass);
                passs= resultSet.getString("password");
                if(npass.equals(passs)){
                JOptionPane.showMessageDialog(null,"you currently using this password");
                password.setText("");
                }
               
                return true;
            }
            else{
                System.out.println("safe");
                return false;
            }
            
        } catch (SQLException ex) {
            System.out.println(""+ex);
            return false;
        }
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        edit = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        uname = new javax.swing.JLabel();
        utype = new javax.swing.JLabel();
        usertype = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        newpass = new javax.swing.JPasswordField();
        password = new javax.swing.JPasswordField();
        warning = new javax.swing.JLabel();
        showpass = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        edit.setBackground(new java.awt.Color(0, 153, 0));
        edit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edit.setForeground(new java.awt.Color(255, 255, 255));
        edit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        edit.setText("SAVE");
        edit.setOpaque(true);
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        jPanel1.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 210, 50));

        back.setBackground(new java.awt.Color(0, 153, 0));
        back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setText("BACK");
        back.setOpaque(true);
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 190, 40));

        uname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        uname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 570, 490, 30));

        utype.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        utype.setForeground(new java.awt.Color(255, 255, 255));
        utype.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(utype, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 200, 40));

        usertype.setBackground(new java.awt.Color(0, 153, 0));
        usertype.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        usertype.setForeground(new java.awt.Color(255, 255, 255));
        usertype.setText(" EDIT MY ACCOUNT");
        usertype.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        usertype.setOpaque(true);
        jPanel1.add(usertype, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 0));
        jLabel13.setText("new password:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 350, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 0));
        jLabel8.setText("old password:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 350, -1));
        jPanel1.add(newpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 460, 40));
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 460, 40));

        warning.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        warning.setForeground(new java.awt.Color(204, 0, 0));
        warning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(warning, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 340, 30));

        showpass.setBackground(new java.awt.Color(255, 255, 255));
        showpass.setText("Show password");
        showpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassActionPerformed(evt);
            }
        });
        jPanel1.add(showpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 420, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        back.setOpaque(true);
        back.setBackground(Color.white);
        back.setForeground(new java.awt.Color(0,153,0));

        if(utype.getText().equals("Admin")){
                Admin_dashboard admdash = new Admin_dashboard();
                admdash.setVisible(true);
               this.dispose();
               
        }else if(utype.getText().equals("User")){
                User_dashboard usrdash = new User_dashboard();
                usrdash.setVisible(true);
                this.dispose();            
            }
    }//GEN-LAST:event_backMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       Session sess = Session.getInstance();
        if(sess.getId() == 0){
        JOptionPane.showMessageDialog(null,"No account found, login first!");
        login lfm = new login();
        lfm.setVisible(true);
        this.dispose();
        }else{
        
        utype.setText(""+sess.getType());
        

        }
    }//GEN-LAST:event_formWindowActivated

    private void editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseClicked
      Session sess = Session.getInstance();     
             dbconnect dbc = new dbconnect();
        try {
            
              if(password.getText().isEmpty() || newpass.getText().isEmpty()){
                   JOptionPane.showMessageDialog(null,"all field are required");
                  }
              else if(duplicatecheck()){}
                 else if (!(newpass.getText().length() >= 8)){ 
                JOptionPane.showMessageDialog(null,"password should be above 8 digits");
                 }
                 else {   
                     String hpass = passwordHasher.hashPassword(newpass.getText());
                    dbc.insertData("UPDATE users SET password ='"+hpass+"' WHERE userid ='"+sess.getId()+"'");
                    JOptionPane.showMessageDialog(null,"password updated successfully.");

                login all = new login();
                all.setVisible(true);
                this.dispose();}
            
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(editpass.class.getName()).log(Level.SEVERE, null, ex);
        }
            

    }//GEN-LAST:event_editMouseClicked

    private void showpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassActionPerformed
        if(showpass.isSelected()){
            password.setEchoChar((char)0);
            newpass.setEchoChar((char)0);
        }  else {
            password.setEchoChar('*');
            newpass.setEchoChar('*');
        }        // TODO add your handling code here:
    }//GEN-LAST:event_showpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editpass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    public javax.swing.JLabel edit;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField newpass;
    private javax.swing.JPasswordField password;
    private javax.swing.JCheckBox showpass;
    private javax.swing.JLabel uname;
    private javax.swing.JLabel usertype;
    private javax.swing.JLabel utype;
    private javax.swing.JLabel warning;
    // End of variables declaration//GEN-END:variables
}
