/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user_interface;

import admin_interface.*;
import config.Session;
import cruduser.allusers;
import cruduser.profileinfo;
import java.awt.Color;
import javax.swing.JOptionPane;
import psms.mariquit.login;

/**
 *
 * @author Teves
 */
public class User_dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public User_dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        settings = new javax.swing.JLabel();
        pigbutton1 = new javax.swing.JLabel();
        buybutton = new javax.swing.JLabel();
        profile = new javax.swing.JLabel();
        uname = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        utype = new javax.swing.JLabel();
        settings1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        settings.setBackground(new java.awt.Color(0, 153, 0));
        settings.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        settings.setForeground(new java.awt.Color(255, 255, 255));
        settings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        settings.setText("LOG OUT");
        settings.setOpaque(true);
        settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsMouseClicked(evt);
            }
        });
        jPanel1.add(settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 300, 60));

        pigbutton1.setBackground(new java.awt.Color(0, 153, 0));
        pigbutton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pigbutton1.setForeground(new java.awt.Color(255, 255, 255));
        pigbutton1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pigbutton1.setText("PIG");
        pigbutton1.setOpaque(true);
        jPanel1.add(pigbutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 300, 60));

        buybutton.setBackground(new java.awt.Color(0, 153, 0));
        buybutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buybutton.setForeground(new java.awt.Color(255, 255, 255));
        buybutton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buybutton.setText("BUY");
        buybutton.setOpaque(true);
        jPanel1.add(buybutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 300, 60));

        profile.setBackground(new java.awt.Color(0, 153, 0));
        profile.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        profile.setForeground(new java.awt.Color(255, 255, 255));
        profile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profile.setText("PROFILE");
        profile.setOpaque(true);
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
        });
        jPanel1.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 300, 60));

        uname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        uname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 550, 490, 30));

        jLabel8.setBackground(new java.awt.Color(0, 153, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PIG SALE MANAGEMENT SYSTEM - USERS DASHBOARD");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel8.setOpaque(true);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENU");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 300, 50));

        utype.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        utype.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(utype, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 510, 200, 30));

        settings1.setBackground(new java.awt.Color(0, 153, 0));
        settings1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        settings1.setForeground(new java.awt.Color(255, 255, 255));
        settings1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        settings1.setText("SETTINGS");
        settings1.setOpaque(true);
        jPanel1.add(settings1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 300, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pigimage.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 260, 180));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PIG SALES MANAGEMENT SYSTEM");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 220, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 68)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("PSMS");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, 220, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked
        profile.setOpaque(true);
        profile.setBackground(Color.white);
        profile.setForeground(new java.awt.Color(0,153,0));
        profileinfo info = new profileinfo();
        info.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_profileMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Session sess = Session.getInstance();
        if(sess.getId() == 0){
        JOptionPane.showMessageDialog(null,"No account found, login first!");
        login lfm = new login();
        lfm.setVisible(true);
        this.dispose();
        }else{
        uname.setText("Username: "+sess.getUsername());
        utype.setText("Usertype: "+sess.getType());
        
        }        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void settingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMouseClicked
                System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_settingsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buybutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pigbutton1;
    private javax.swing.JLabel profile;
    private javax.swing.JLabel settings;
    private javax.swing.JLabel settings1;
    private javax.swing.JLabel uname;
    private javax.swing.JLabel utype;
    // End of variables declaration//GEN-END:variables
}
