/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cruduser;

import admin_interface.Admin_dashboard;
import config.Session;
import config.dbconnect;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableColumnModel;
import net.proteanit.sql.DbUtils;
import psms.mariquit.login;
import user_interface.User_dashboard;

/**
 *
 * @author Teves
 */
public class allusers extends javax.swing.JFrame {

    /**
     * Creates new form allusers
     */
    public allusers() {
        initComponents();
        displayData();
       userstable.getTableHeader().setOpaque(false);
       userstable.getTableHeader().setBackground(new java.awt.Color(0,153,0));

    }   
        public void displayData(){
        try{
            dbconnect dbc = new dbconnect();
            try (ResultSet rs = dbc.getData("SELECT userid, fullname, email, usertype, status FROM users")) {
                userstable.setModel(DbUtils.resultSetToTableModel(rs));

                TableColumnModel columnModel = userstable.getColumnModel();
                columnModel.getColumn(0).setHeaderValue("ID");
                columnModel.getColumn(1).setHeaderValue("Full name");
                columnModel.getColumn(2).setHeaderValue("Email");
                columnModel.getColumn(3).setHeaderValue("User type");
                columnModel.getColumn(4).setHeaderValue("User status");
                userstable.getTableHeader().repaint();
                
            }
        }catch(SQLException ex){
            System.out.println("Errors: "+ex.getMessage());

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        userbutton = new javax.swing.JLabel();
        pigbutton1 = new javax.swing.JLabel();
        buybutton = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        uname = new javax.swing.JLabel();
        utype = new javax.swing.JLabel();
        usertype = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        profile1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userstable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userbutton.setBackground(new java.awt.Color(0, 153, 0));
        userbutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        userbutton.setForeground(new java.awt.Color(255, 255, 255));
        userbutton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userbutton.setText("ADD USER");
        userbutton.setOpaque(true);
        userbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userbuttonMouseClicked(evt);
            }
        });
        jPanel1.add(userbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 300, 60));

        pigbutton1.setBackground(new java.awt.Color(0, 153, 0));
        pigbutton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pigbutton1.setForeground(new java.awt.Color(255, 255, 255));
        pigbutton1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pigbutton1.setText("EDIT USER");
        pigbutton1.setOpaque(true);
        jPanel1.add(pigbutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 300, 60));

        buybutton.setBackground(new java.awt.Color(0, 153, 0));
        buybutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buybutton.setForeground(new java.awt.Color(255, 255, 255));
        buybutton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buybutton.setText("DELETE USER");
        buybutton.setOpaque(true);
        jPanel1.add(buybutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 300, 60));

        back.setBackground(new java.awt.Color(0, 153, 0));
        back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setText("BACK");
        back.setOpaque(true);
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 300, 60));

        uname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        uname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 570, 490, 30));

        utype.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        utype.setForeground(new java.awt.Color(255, 255, 255));
        utype.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(utype, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 200, 40));

        usertype.setBackground(new java.awt.Color(0, 153, 0));
        usertype.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        usertype.setForeground(new java.awt.Color(255, 255, 255));
        usertype.setText("MANAGE USERS");
        usertype.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        usertype.setOpaque(true);
        jPanel1.add(usertype, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("OPTIONS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 300, 50));

        profile1.setBackground(new java.awt.Color(0, 153, 0));
        profile1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        profile1.setForeground(new java.awt.Color(255, 255, 255));
        profile1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profile1.setText("VIEW DETAIL");
        profile1.setOpaque(true);
        profile1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profile1MouseClicked(evt);
            }
        });
        jPanel1.add(profile1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 300, 60));

        userstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        userstable.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(userstable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 760, 570));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userbuttonMouseClicked
        userbutton.setOpaque(true);
        userbutton.setBackground(Color.white);
        userbutton.setForeground(new java.awt.Color(0,153,0));

        back.setOpaque(true);
        back.setForeground(Color.white);
        back.setBackground(new java.awt.Color(0,153,0));

    }//GEN-LAST:event_userbuttonMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        back.setOpaque(true);
        back.setBackground(Color.white);
        back.setForeground(new java.awt.Color(0,153,0));

        if(utype.getText().equals("Admin")){
                Admin_dashboard admdash = new Admin_dashboard();
                admdash.setVisible(true);
               this.dispose();
               
        }else if(utype.getText().equals("User")){
                User_dashboard usrdash = new User_dashboard();
                usrdash.setVisible(true);
                this.dispose();            
            }
    }//GEN-LAST:event_backMouseClicked

    private void profile1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profile1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_profile1MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       Session sess = Session.getInstance();
        if(sess.getId() == 0){
        JOptionPane.showMessageDialog(null,"No account found, login first!");
        login lfm = new login();
        lfm.setVisible(true);
        this.dispose();
        }else{
        
        utype.setText(""+sess.getType());

        }
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(allusers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(allusers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(allusers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(allusers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new allusers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel buybutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pigbutton1;
    private javax.swing.JLabel profile1;
    private javax.swing.JLabel uname;
    private javax.swing.JLabel userbutton;
    private javax.swing.JTable userstable;
    private javax.swing.JLabel usertype;
    private javax.swing.JLabel utype;
    // End of variables declaration//GEN-END:variables
}
